In [ ]:
Todays task :
    q1 : Try to print a prime number in between 1 to 1000
    q2 : Try to write a function which  is equivalent  to print function in python
    q3 : Try to write a function which is a replica of list append , extend and pop function 
    q4 : Try to write a lambda function which can return a concatination of all the string that we will pass
    q5 : Try to write a lambda function which can return list of square of all the data between 1-100 
    q6 : Try to write a 10 Different different example of lambda function with a choice of your taks 
    q7 : Try to wwrite a funtion whihc can perform a read operation from .txt file 
        
        shivan@ineuron.ai
        sudhashu@ineuron.ai

In [21]:
#    q1 : Try to print a prime number in between 1 to 1000
def pn():
    l=[]
    for i in range(2,1001):
        for  j in range( 2,i+1):
            if i%j ==0 :    
                if j !=i :
                    break
                elif j==i :
                    l.append(j)
    return (l)
                    
                
        

In [59]:
l= pn()


In [60]:
l

[2,
 3,
 5,
 7,
 11,
 13,
 17,
 19,
 23,
 29,
 31,
 37,
 41,
 43,
 47,
 53,
 59,
 61,
 67,
 71,
 73,
 79,
 83,
 89,
 97,
 101,
 103,
 107,
 109,
 113,
 127,
 131,
 137,
 139,
 149,
 151,
 157,
 163,
 167,
 173,
 179,
 181,
 191,
 193,
 197,
 199,
 211,
 223,
 227,
 229,
 233,
 239,
 241,
 251,
 257,
 263,
 269,
 271,
 277,
 281,
 283,
 293,
 307,
 311,
 313,
 317,
 331,
 337,
 347,
 349,
 353,
 359,
 367,
 373,
 379,
 383,
 389,
 397,
 401,
 409,
 419,
 421,
 431,
 433,
 439,
 443,
 449,
 457,
 461,
 463,
 467,
 479,
 487,
 491,
 499,
 503,
 509,
 521,
 523,
 541,
 547,
 557,
 563,
 569,
 571,
 577,
 587,
 593,
 599,
 601,
 607,
 613,
 617,
 619,
 631,
 641,
 643,
 647,
 653,
 659,
 661,
 673,
 677,
 683,
 691,
 701,
 709,
 719,
 727,
 733,
 739,
 743,
 751,
 757,
 761,
 769,
 773,
 787,
 797,
 809,
 811,
 821,
 823,
 827,
 829,
 839,
 853,
 857,
 859,
 863,
 877,
 881,
 883,
 887,
 907,
 911,
 919,
 929,
 937,
 941,
 947,
 953,
 967,
 971,
 977,
 983,
 991,
 997]

In [81]:
 # q2 : Try to write a function which  is equivalent  to print function in python

import sys, functools

nl = "\n"

def StreamOut(stream, *s, **kw):
    k = kw.setdefault
    # Process keyword arguments
    sep     = k("sep", "")
    auto_nl = k("auto_nl", True)
    prefix  = k("prefix", "")
    convert = k("convert", str)
    end =     k( "end",'\n')


    # Convert position arguments to strings
    strings = map(convert, s)
    # Dump them to the stream
    stream.write(prefix + sep.join(strings))
    # Add a newline if desired
    if auto_nl:
        stream.write(nl)
    

out  = functools.partial(StreamOut, sys.stdout)
outs = functools.partial(StreamOut, sys.stdout, sep=" ")
dbg  = functools.partial(StreamOut, sys.stdout, sep=" ", prefix="+ ")
err  = functools.partial(StreamOut, sys.stderr)

out("Hi there", "how are you?", sep= "," )
outs("Hi there", "how are you?")

Hi there,how are you?
Hi there how are you?


In [100]:
 #q3 : Try to write a function which is a replica of list append , extend and pop function
def append_extend(l1,l2):
    l =l1 + l2
    print(l) 
def pop_(l1,l2):
    l=l1[:-1]
    print(l)
def extend()


In [104]:
a= input().split(",")
b=[input()]
append_extend(a,b)# append
c=input().split(",")
append_extend(a,b)# extend


1,2,3,4
1
['1', '2', '3', '4', '1']


In [102]:
a= input().split(",")
pop_(a)#pop

ass.as.d,w,e,e,w,d
d
['ass.as.d', 'w', 'e', 'e', 'w']


In [95]:
# q4 : Try to write a lambda function which can return a concatination of all the string that we will pass

n= lambda *a:''.join([i  for i in a ]) # join is used to concatinate


In [92]:
n1=lambda a,b : a+b

In [144]:
n("hiajqss","zjabjab","jkkjbajxbajbx")

'hiajqsszjabjabjkkjbajxbajbx'

In [94]:
n1("hi","noooo")

'hinoooo'

In [162]:
#q5 : Try to write a lambda function which can return list of square of all the data between 1-100 
t=lambda x:[i**2 for i in range(1,x+1)]

In [163]:
t(100)

[1,
 4,
 9,
 16,
 25,
 36,
 49,
 64,
 81,
 100,
 121,
 144,
 169,
 196,
 225,
 256,
 289,
 324,
 361,
 400,
 441,
 484,
 529,
 576,
 625,
 676,
 729,
 784,
 841,
 900,
 961,
 1024,
 1089,
 1156,
 1225,
 1296,
 1369,
 1444,
 1521,
 1600,
 1681,
 1764,
 1849,
 1936,
 2025,
 2116,
 2209,
 2304,
 2401,
 2500,
 2601,
 2704,
 2809,
 2916,
 3025,
 3136,
 3249,
 3364,
 3481,
 3600,
 3721,
 3844,
 3969,
 4096,
 4225,
 4356,
 4489,
 4624,
 4761,
 4900,
 5041,
 5184,
 5329,
 5476,
 5625,
 5776,
 5929,
 6084,
 6241,
 6400,
 6561,
 6724,
 6889,
 7056,
 7225,
 7396,
 7569,
 7744,
 7921,
 8100,
 8281,
 8464,
 8649,
 8836,
 9025,
 9216,
 9409,
 9604,
 9801,
 10000]

In [ ]:
 #q6 : Try to write a 10 Different different example of lambda function with a choice of your taks 
    
    
    

In [2]:
a1=lambda x,y: x*y

In [3]:
a1(1,2)

2

In [15]:
a2=lambda x: [i for i in x]

In [16]:
a2("hi how are you")

['h', 'i', ' ', 'h', 'o', 'w', ' ', 'a', 'r', 'e', ' ', 'y', 'o', 'u']

In [18]:
a3=lambda x: (" ").join([str(i) for i in x])

In [19]:
a3("hi how are you")

'h i   h o w   a r e   y o u'

In [38]:
a4 = lambda x: [int(i) for i in range(1,x+1,2)]

In [39]:
print("odd number till 100")
a4(100)

[1,
 3,
 5,
 7,
 9,
 11,
 13,
 15,
 17,
 19,
 21,
 23,
 25,
 27,
 29,
 31,
 33,
 35,
 37,
 39,
 41,
 43,
 45,
 47,
 49,
 51,
 53,
 55,
 57,
 59,
 61,
 63,
 65,
 67,
 69,
 71,
 73,
 75,
 77,
 79,
 81,
 83,
 85,
 87,
 89,
 91,
 93,
 95,
 97,
 99]

In [40]:
a5 = lambda x: [int(i) for i in range(0,x+1,2)]

In [41]:
print("even number till 100")
a5(100)

even number till 100


[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100]

In [54]:
a6 = lambda **x: tuple([i for i in x.items()])

In [55]:
a6(
  brand= "Ford",
  model= "Mustang",
  year= 1964
)

(('brand', 'Ford'), ('model', 'Mustang'), ('year', 1964))

In [80]:
import numpy as np
a7 = lambda x: x.reshape(6,1)

In [77]:
a=np.array([[1,2,3],[1,23,5]])


In [79]:
a.shape

(2, 3)

In [81]:
a7(a)

array([[ 1],
       [ 2],
       [ 3],
       [ 1],
       [23],
       [ 5]])

In [82]:
a8 = lambda x: x+1

In [83]:
a8(a)

array([[ 2,  3,  4],
       [ 2, 24,  6]])

In [89]:
a9= lambda x: x/0

In [90]:
a9(a)# no errror

C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[inf, inf, inf],
       [inf, inf, inf]])

In [21]:
#q7 : Try to wwrite a funtion whihc can perform a read operation from .txt file 
import os 
with open(r"D:\d+Project\sample-text-file.txt",'r') as f:
    lines = f.readlines()



In [6]:
lines

['Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, \n',
 'quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. \n',
 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. \n',
 'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.']